services:
  # USERS DB
  postgres_users:
    image: postgres:16-alpine
    container_name: eventflow-user-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${USERS_DB}
    ports:
      - "${USERS_PORT}:5432"
    volumes:
      - pg_users_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${USERS_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  # EVENTS DB
  postgres_events:
    image: postgres:16-alpine
    container_name: eventflow-events-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${EVENTS_DB}
    ports:
      - "${EVENTS_PORT}:5432"
    volumes:
      - pg_events_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${EVENTS_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  # BOOKING DB
  postgres_booking:
    image: postgres:16-alpine
    container_name: ventflow-booking-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${BOOKING_DB}
    ports:
      - "${BOOKING_PORT}:5432"
    volumes:
      - pg_booking_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${BOOKING_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      
volumes:
  pg_users_data:
  pg_events_data:
  pg_booking_data: