{
 "title": "Observability Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Запросов в обработке Users API",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_active_requests{job=\"users-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Запросов в обработке Events API",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_active_requests{job=\"events-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "запросов в обработке Booking API",
   "type": "stat",
   "description": "Текущее количество запросов в обработке",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_active_requests{job=\"bookings-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate ",
   "type": "timeseries",
   "description": "Error Rate фиксирует количество сбойных запросов в системе. ",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\"}[$__rate_interval])) \r\n/ \r\nsum(rate(http_server_request_duration_seconds_count[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Latency измеряет время, необходимое приложению для обработки запроса. ",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput (RPS)",
   "type": "timeseries",
   "description": "Throughput показывает количество запросов, обрабатываемых приложением в единицу времени (обычно в секунду), то есть текущее количество запросов к серверу в секунду (RPS).",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "requests/second" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"users-service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"bookings-service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{job=\"events-service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}