apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://eventflow-prometheus:9090
    isDefault: true
    editable: false

  - name: jaeger
    type: jaeger
    access: proxy
    url: http://eventflow-jaeger:16686
    editable: false