{
 "title": "Observability Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Thread Pool Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dotnet_thread_pool_queue_length_total",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GC Collections Rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(gc_heap_generation, job) (rate(dotnet_gc_collections_total{job=~\"users-service|events-service|bookings-service\"}[5m]))",
     "legendFormat": "{{job}} - {{gc_heap_generation}}"
    }
   ]
  },
  {
   "title": "Error Rate ",
   "type": "timeseries",
   "description": "Error Rate фиксирует количество сбойных запросов в системе. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\"}[$__rate_interval])) \r\n/ \r\nsum(rate(http_server_request_duration_seconds_count[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "description": "Latency измеряет время, необходимое приложению для обработки запроса. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, job) (rate(http_server_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Quantile 0.99 - {{job}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, job) (rate(http_server_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Quantile 0.95 - {{job}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, job) (rate(http_server_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "Quantile 0.50 - {{job}}"
    }
   ]
  },
  {
   "title": "Throughput (RPS)",
   "type": "timeseries",
   "description": "Throughput показывает количество запросов, обрабатываемых приложением в единицу времени (обычно в секунду), то есть текущее количество запросов к серверу в секунду (RPS).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "requests/second" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "Common"
    },
    {
     "expr": "sum by(job) (rate(http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}