FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY . .

RUN dotnet restore "EventFlow.Bookings/EventFlow.Bookings.Presentation/EventFlow.Bookings.Presentation.csproj"
RUN dotnet publish "EventFlow.Bookings/EventFlow.Bookings.Presentation/EventFlow.Bookings.Presentation.csproj" \
    -c Debug \
    -o /app/publish \
    /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Development

EXPOSE 8080

ENTRYPOINT ["dotnet", "EventFlow.Bookings.Presentation.dll"]